name: Build Cronet Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    defaults:
      run:
        shell: bash
        working-directory: src

    env:
      EXTRA_FLAGS: 'target_cpu="x64"'
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
      - uses: actions/checkout@v4

      - name: Cache LLVM & GN
        uses: actions/cache@v4
        with:
          path: |
            src/third_party/llvm-build/Release+Asserts
            src/gn
            ~/.cargo/bin
            ~/bin/ninja.exe
          key: toolchain-${{ hashFiles('CHROMIUM_VERSION') }}

      - name: Cache Windows PGO
        uses: actions/cache@v4
        with:
          path: src/chrome/build/pgo_profiles/chrome-win64-*
          key: pgo-${{ hashFiles('CHROMIUM_VERSION') }}

      - name: Install Ninja
        run: |
          mkdir -p ~/bin
          if [ ! -f ~/bin/ninja.exe ]; then
            curl -L https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip -o ninja.zip
            unzip ninja.zip -d ~/bin
          fi
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Download Clang
        run: ./get-clang.sh

      - name: Build
        run: ./build.sh

      - name: Package
        run: |
          cd out
          7z a ../../cronet-windows-x64.zip *

      - uses: actions/upload-artifact@v4
        with:
          name: cronet-windows-x64
          path: cronet-windows-x64.zip
