name: Build Cronet

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: src

jobs:
  build:
    runs-on: windows-2022

    env:
      EXTRA_FLAGS: 'target_cpu="x64"'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Clang
        run: ./get-clang.sh

      - name: Generate Build Files
        run: |
          export TMPDIR="$PWD/tmp"
          rm -rf "$TMPDIR"
          mkdir -p "$TMPDIR"

          export DEPOT_TOOLS_WIN_TOOLCHAIN=0

          ./gn/out/gn gen out/Release --args="
            is_official_build=true
            is_chrome_branded=true
            is_clang=true
            use_sysroot=false
            is_cronet_build=true
            target_cpu=\"x64\"
          "

      - name: Build Cronet
        run: |
          autoninja -C out/Release cronet_package

      - name: List Release Directory
        run: |
          ls -R out/Release

      - name: Upload Release Folder
        uses: actions/upload-artifact@v4
        with:
          name: cronet-release
          path: src/out/Release/
          if-no-files-found: error
